In [55]:
import numpy as np
import pandas as pd

In [56]:
training_set = pd.read_csv('train.csv')
testing_set = pd.read_csv('test.csv')

In [57]:
training_set.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [58]:
training_set['FamilySize'] = training_set['SibSp'] + training_set['Parch'] + 1
testing_set['FamilySize'] = testing_set['SibSp'] + testing_set['Parch'] + 1

In [59]:
training_set.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

In [60]:
training_set.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
FamilySize       0
dtype: int64

In [61]:
training_set['Age'].fillna(training_set['Age'].median(), inplace=True)
testing_set['Age'].fillna(testing_set['Age'].median(),inplace=True)

/tmp/ipykernel_53949/2452318294.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  training_set['Age'].fillna(training_set['Age'].median(), inplace=True)
/tmp/ipykernel_53949/2452318294.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  testing_set['Age'].fillna(testing_set['Age'].median(),inplace=True)

In [62]:
testing_set[testing_set['Fare'].isna()]

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
152,1044,3,"Storey, Mr. Thomas",male,60.5,0,0,3701,NaN,NaN,S,1

In [63]:
testing_set['Fare'].fillna(testing_set[testing_set['Pclass'] == 3]['Fare'].median(), inplace=True)

/tmp/ipykernel_53949/1362121932.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  testing_set['Fare'].fillna(testing_set[testing_set['Pclass'] == 3]['Fare'].median(), inplace=True)

In [64]:
testing_set.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
FamilySize       0
dtype: int64

In [65]:
training_set['Embarked'].fillna(training_set['Embarked'].mode()[0], inplace=True)

/tmp/ipykernel_53949/372061332.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  training_set['Embarked'].fillna(training_set['Embarked'].mode()[0], inplace=True)

In [66]:
training_set.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
FamilySize       0
dtype: int64

In [67]:
for series in (training_set,testing_set):
    series.drop(['PassengerId' ,'Name', 'Ticket', 'SibSp', 'Parch', 'Cabin'], axis=1,inplace=True)

In [68]:
training_set = pd.get_dummies(training_set,columns=['Embarked'], dtype=int)
testing_set = pd.get_dummies(testing_set,columns=['Embarked'], dtype=int)

In [69]:
for series in (training_set, testing_set):
    series['Sex'] = series['Sex'].map({"female" : 0, "male" : 1})

In [70]:
training_set.head()

,Survived,Pclass,Sex,Age,Fare,FamilySize,Embarked_C,Embarked_Q,Embarked_S
0,0,3,1,22.0,7.2500,2,0,0,1
1,1,1,0,38.0,71.2833,2,1,0,0
2,1,3,0,26.0,7.9250,1,0,0,1
3,1,1,0,35.0,53.1000,2,0,0,1
4,0,3,1,35.0,8.0500,1,0,0,1

In [71]:
for series in (training_set, testing_set):
    series['Pclass'] = (series['Pclass'] - series['Pclass'].min()) / (series['Pclass'].max() - series['Pclass'].min())
    series['Age'] = (series['Age'] - series['Age'].min()) / (series['Age'].max() - series['Age'].min())
    series['Fare'] = (series['Fare'] - series['Fare'].min()) / (series['Fare'].max() - series['Fare'].min())
    series['FamilySize'] = (series['FamilySize'] - series['FamilySize'].min()) / (series['FamilySize'].max() - series['FamilySize'].min())

In [72]:
training_set.head()

,Survived,Pclass,Sex,Age,Fare,FamilySize,Embarked_C,Embarked_Q,Embarked_S
0,0,1.0,1,0.271174,0.014151,0.1,0,0,1
1,1,0.0,0,0.472229,0.139136,0.1,1,0,0
2,1,1.0,0,0.321438,0.015469,0.0,0,0,1
3,1,0.0,0,0.434531,0.103644,0.1,0,0,1
4,0,1.0,1,0.434531,0.015713,0.0,0,0,1

In [73]:
training_set.to_csv('train_cleaned.csv', index=False)
testing_set.to_csv('test_cleaned.csv', index=False)